---
- name: Set up production environment
  hosts: all
  become: true
  vars:
    command_log_file: "/var/log/command_log"
  roles:
    - role: "../ansible-role-docker"
      vars:
        docker_logging_driver: "json-file"
        docker_storage_driver: "overlay2"
  tasks:
    - name: Tune the server for high network traffic
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { name: 'net.core.somaxconn', value: '65535' }
        - { name: 'net.core.netdev_max_backlog', value: '250000' }
        - { name: 'net.ipv4.tcp_max_syn_backlog', value: '250000' }
        - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
        - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }

    - name: Ensure /etc/profile is configured for command line audit logging
      blockinfile:
        path: /etc/profile
        block: |
          #log all your bash command to syslog
          function log2syslog
          {
            declare COMMAND
            COMMAND=$(fc -ln -0)
            logger -p local1.notice -t bash -i -- "${USER}:${COMMAND}"
          }
          trap log2syslog DEBUG
        state: present
        insertafter: EOF

    - name: Configure rsyslog for local logging
      blockinfile:
        path: /etc/rsyslog.conf
        block: |
          local1.*                                          -{{ command_log_file }}
        state: present
        insertafter: EOF

    - name: Restart rsyslog service to apply changes
      service:
        name: rsyslog
        state: restarted