---
- name: Set up production environment
  hosts: all
  become: true
  vars:
    docker_logging_driver: "json-file"
    docker_storage_driver: "overlay2"
    command_log_file: "/var/log/command_log"
  roles:
  - role: "../ansible-role-docker"
  tasks:
  #   - name: Tune the server for high network traffic
  #     sysctl:
  #       name: "{{ item.name }}"
  #       value: "{{ item.value }}"
  #       state: present
  #     loop:
  #       - { name: 'net.core.somaxconn', value: '65535' }
  #       - { name: 'net.core.netdev_max_backlog', value: '250000' }
  #       - { name: 'net.ipv4.tcp_max_syn_backlog', value: '250000' }
  #       - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
  #       - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
  #     notify:
  #       - reload sysctl

  #   - name: Configure command logging for all users
  #     lineinfile:
  #       path: /etc/profile
  #       line: 'export PROMPT_COMMAND=\'{ date "+%Y-%m-%d %T $(whoami) $(history 1)" >> {{ command_log_file }} }\''

  #   - name: Ensure the command log file exists
  #     file:
  #       path: "{{ command_log_file }}"
  #       state: touch
  #       owner: root
  #       group: root
  #       mode: '0644'

  # handlers:
  #   - name: reload sysctl
  #     command: sysctl -p